version: "3"
services:
    tse_servicio_recepcion_fallecidos_dev:
      image: "tse_servicio_recepcion_fallecidos_dev:latest"
      deploy:
        replicas: 5
      ports:
       - "5021-5025:5021"
      restart: unless-stopped
      networks:
      - default
      environment:
        - BD_URL=jdbc:oracle:thin:@//100.100.1.102:1521/DESA
        - BD_USER=FALLE_RENAP_WS
        - BD_PASSWORD=F@11ERENAPWS
        - SSO_API_URL=http://192.168.79.67:9763
        - FILES_API_URL=http://192.168.79.66:3005
        - CERTIFICATE_API_URL=http://192.168.79.66:3003
        - CERTIFICATE_SIGN_URL= http://192.168.79.66:5000
        - REQUEST_ROUTE=reportes_fallecidos_renap_dev
        - TZ=America/Guatemala
        
      volumes:
         - /etc/localtime:/etc/localtime:ro
         - /etc/timezone:/etc/timezone:ro