version: "3.0"
services:
    tse_padron_api_prod:
      container_name: tse_padron_api_prod
      build:
        context: .
      image: tse_padron_api_prod
      restart: unless-stopped
      ports:
      - "5004:5004"
      networks:
        default:
          ipv4_address: 172.24.0.6
      environment:
        - BD_URL=jdbc:oracle:thin:@//192.168.79.134:1521/WEBCP
        - BD_USER=WEBCERTIFICACION
        - BD_PASSWORD=TDtu5#43A
        - SSO_API_URL=http://192.168.79.67:9762
        - FILES_API_URL=http://192.168.79.131:3005
      
networks:
  default:
    external:
      name: tse_internal
